"""
otf_custom_degradations.py — Runtime patcher for NeoSR / traiNNer-Redux

Injects custom degradations into the OTF pipeline (after standard degradations,
before the queue). Reads params from the loaded config / sidecar JSON.

Custom 1 degradations:
  banding, posterize, chroma_subsampling, chromatic_aberration,
  halation, salt_pepper, vhs

Custom 2 degradations:
  aliasing, interlace_weave, interlace_flicker, interlace_blend,
  film_grain, oversharpening, scanlines

Usage:
    Called automatically by tab_run before training launches.
    Writes a small wrapper file to the engine's data/ directory that monkey-patches
    the feed_data method of the OTF dataset class.
"""
import os
import shutil

PATCH_FILENAME = "_usr_studio_custom_degradations.py"

PATCH_CODE = '''"""
Auto-generated by Universal SR Studio.
DO NOT EDIT — regenerated each training launch.

Custom degradations: banding, posterize, chroma subsampling,
chromatic aberration, halation, salt & pepper, VHS/analog,
aliasing, interlacing, film grain, oversharpening, scanlines.
"""
import torch
import torch.nn.functional as F
import random


def apply_posterize(tensor: torch.Tensor, bits: int) -> torch.Tensor:
    """Reduce per-channel bit depth (1-8). Tensor [0,1] BCHW."""
    if bits >= 8:
        return tensor
    levels = 2 ** bits
    return (torch.round(tensor * (levels - 1)) / (levels - 1)).clamp(0.0, 1.0)


def apply_banding(tensor: torch.Tensor, levels: int) -> torch.Tensor:
    """Palette quantization — creates banding in smooth gradients. BCHW [0,1]."""
    if levels >= 256:
        return tensor
    per_channel = max(2, int(round(levels ** (1.0 / 3.0))))
    return (torch.round(tensor * (per_channel - 1)) / (per_channel - 1)).clamp(0.0, 1.0)


def apply_chroma_subsampling(tensor: torch.Tensor) -> torch.Tensor:
    """Simulate 4:2:0 chroma subsampling (YCbCr chroma downsample 2x then upsample)."""
    B, C, H, W = tensor.shape
    if C != 3:
        return tensor
    R, G, Bc = tensor[:, 0:1], tensor[:, 1:2], tensor[:, 2:3]
    Y  =  0.299 * R + 0.587 * G + 0.114 * Bc
    Cb = -0.169 * R - 0.331 * G + 0.500 * Bc + 0.5
    Cr =  0.500 * R - 0.419 * G - 0.081 * Bc + 0.5
    Cb_u = F.interpolate(F.avg_pool2d(Cb, 2, stride=2), (H, W), mode="nearest")
    Cr_u = F.interpolate(F.avg_pool2d(Cr, 2, stride=2), (H, W), mode="nearest")
    cb, cr = Cb_u - 0.5, Cr_u - 0.5
    return torch.cat([Y + 1.402 * cr,
                      Y - 0.344 * cb - 0.714 * cr,
                      Y + 1.772 * cb], dim=1).clamp(0.0, 1.0)


def apply_chromatic_aberration(tensor: torch.Tensor, shift: int) -> torch.Tensor:
    """Shift R and B channels in opposite horizontal directions."""
    if tensor.shape[1] < 3 or shift == 0:
        return tensor
    result = tensor.clone()
    result[:, 0] = torch.roll(tensor[:, 0],  shift, dims=3)
    result[:, 2] = torch.roll(tensor[:, 2], -shift, dims=3)
    return result.clamp(0.0, 1.0)


def apply_halation(tensor: torch.Tensor, strength: float) -> torch.Tensor:
    """Film halation: bright areas bleed warm glow into surrounding pixels."""
    ks = 11
    bright = (tensor.mean(dim=1, keepdim=True) > 0.65).float()
    glow = F.avg_pool2d(tensor * bright, kernel_size=ks, stride=1, padding=ks // 2)
    return (tensor + glow * strength).clamp(0.0, 1.0)


def apply_salt_pepper(tensor: torch.Tensor, amount: float) -> torch.Tensor:
    """Random black and white pixels (salt & pepper noise)."""
    B, C, H, W = tensor.shape
    mask = torch.rand(B, 1, H, W, device=tensor.device, dtype=tensor.dtype)
    salt   = (mask < amount * 0.5).expand(-1, C, -1, -1).float()
    pepper = (mask > 1.0 - amount * 0.5).expand(-1, C, -1, -1).float()
    return (tensor * (1.0 - salt - pepper) + salt).clamp(0.0, 1.0)


def apply_vhs(tensor: torch.Tensor, strength: float) -> torch.Tensor:
    """VHS/analog artifacts: chroma color bleeding + horizontal scanline dropout."""
    B, C, H, W = tensor.shape
    shift = max(1, int(W * 0.015 * strength))
    result = tensor.clone()
    result[:, 1] = torch.roll(tensor[:, 1], shift,     dims=3)
    result[:, 2] = torch.roll(tensor[:, 2], shift * 2, dims=3)
    dropout_prob = strength * 0.25
    line_mask = (torch.rand(B, 1, H, 1, device=tensor.device, dtype=tensor.dtype)
                 > (1.0 - dropout_prob)).float()
    return (result * (1.0 - line_mask * 0.6)).clamp(0.0, 1.0)


def apply_aliasing(tensor: torch.Tensor, scale: float) -> torch.Tensor:
    """Create aliasing artifacts on diagonal lines via nearest-neighbor downscale+upscale.
    Scale < 1.0 = more aliasing (e.g. 0.5 = strong staircase, 0.85 = subtle).
    """
    B, C, H, W = tensor.shape
    small_h = max(1, int(H * scale))
    small_w = max(1, int(W * scale))
    small = F.interpolate(tensor, size=(small_h, small_w), mode="nearest")
    return F.interpolate(small, size=(H, W), mode="nearest")


def apply_interlace_weave(tensor: torch.Tensor, strength: float) -> torch.Tensor:
    """Weave interlacing: replace odd lines with vertically-shifted field.
    Creates comb-teeth artifact on diagonal edges (classic analog interlace).
    """
    shifted = torch.roll(tensor, 1, dims=2)
    mask = torch.zeros(tensor.shape[0], 1, tensor.shape[2], 1,
                       device=tensor.device, dtype=tensor.dtype)
    mask[:, :, 1::2, :] = 1.0
    blended = tensor * (1 - mask) + shifted * mask
    return tensor * (1 - strength) + blended * strength


def apply_interlace_flicker(tensor: torch.Tensor, strength: float) -> torch.Tensor:
    """Field flicker: alternate scanlines are brighter / darker.
    Simulates 50/60 Hz field brightness variation on CRT.
    """
    B, C, H, W = tensor.shape
    flicker = torch.ones(B, 1, H, 1, device=tensor.device, dtype=tensor.dtype)
    flicker[:, :, 0::2, :] = 1.0 + strength
    flicker[:, :, 1::2, :] = 1.0 - strength
    return (tensor * flicker).clamp(0.0, 1.0)


def apply_interlace_blend(tensor: torch.Tensor, strength: float) -> torch.Tensor:
    """Field blending: ghosting / motion blur between two interlaced fields.
    Simulates frame blending from deinterlacing or slow shutter on interlaced source.
    """
    shift = random.choice([1, 2, 3])
    shifted = torch.roll(tensor, shift, dims=2)
    return (tensor * (1.0 - strength * 0.4) + shifted * strength * 0.4).clamp(0.0, 1.0)


def apply_film_grain(tensor: torch.Tensor, strength: float, grain_size: int = 1) -> torch.Tensor:
    """Luminance-dependent structured film grain (peaks at midtones, low in shadows/highlights)."""
    B, C, H, W = tensor.shape
    luma = (0.299 * tensor[:, 0:1] + 0.587 * tensor[:, 1:2] + 0.114 * tensor[:, 2:3])
    grain_weight = 1.0 - (2.0 * luma - 1.0) ** 2
    gs = max(1, int(grain_size))
    if gs > 1:
        nh, nw = max(1, H // gs), max(1, W // gs)
        noise_s = torch.randn(B, C, nh, nw, device=tensor.device, dtype=tensor.dtype)
        noise = F.interpolate(noise_s, size=(H, W), mode="bilinear", align_corners=False)
    else:
        noise = torch.randn(B, C, H, W, device=tensor.device, dtype=tensor.dtype)
    return (tensor + noise * grain_weight * strength).clamp(0.0, 1.0)


def apply_oversharpening(tensor: torch.Tensor, strength: float) -> torch.Tensor:
    """Unsharp mask halos — over-sharpening artifact common in consumer cameras and
    compressed/upscaled video (sharpening applied too aggressively).
    """
    B, C, H, W = tensor.shape
    k = torch.ones(1, 1, 3, 3, device=tensor.device, dtype=tensor.dtype) / 9.0
    k = k.expand(C, 1, 3, 3)
    blurred = F.conv2d(tensor, k, padding=1, groups=C)
    return (tensor + (tensor - blurred) * strength * 3.0).clamp(0.0, 1.0)


def apply_scanlines(tensor: torch.Tensor, spacing: int, strength: float) -> torch.Tensor:
    """CRT/display scanline effect: darken every N-th horizontal line."""
    B, C, H, W = tensor.shape
    sp = max(2, int(spacing))
    mask = torch.ones(B, 1, H, 1, device=tensor.device, dtype=tensor.dtype)
    mask[:, :, ::sp, :] = 1.0 - strength
    return (tensor * mask).clamp(0.0, 1.0)


def custom_degrade(lq_tensor: torch.Tensor, opt: dict) -> torch.Tensor:
    """Apply all active custom degradations to LQ tensor based on opt config."""
    def _p(key):
        return float(opt.get(key, 0.0))

    def _rng(key, default):
        v = opt.get(key, default)
        if isinstance(v, (list, tuple)) and len(v) >= 2:
            return float(v[0]), float(v[1])
        return float(default[0]), float(default[1])

    if _p("posterize_prob") > 0 and random.random() < _p("posterize_prob"):
        lo, hi = _rng("posterize_bits_range", [3, 6])
        lq_tensor = apply_posterize(lq_tensor, random.randint(int(lo), int(hi)))

    if _p("banding_prob") > 0 and random.random() < _p("banding_prob"):
        lo, hi = _rng("banding_levels_range", [16, 64])
        lq_tensor = apply_banding(lq_tensor, random.randint(int(lo), int(hi)))

    if _p("chroma_prob") > 0 and random.random() < _p("chroma_prob"):
        lq_tensor = apply_chroma_subsampling(lq_tensor)

    if _p("ca_prob") > 0 and random.random() < _p("ca_prob"):
        lo, hi = _rng("ca_shift_range", [1, 5])
        lq_tensor = apply_chromatic_aberration(lq_tensor, random.randint(int(lo), int(hi)))

    if _p("halation_prob") > 0 and random.random() < _p("halation_prob"):
        lo, hi = _rng("halation_strength_range", [0.05, 0.3])
        lq_tensor = apply_halation(lq_tensor, random.uniform(lo, hi))

    if _p("salt_pepper_prob") > 0 and random.random() < _p("salt_pepper_prob"):
        lo, hi = _rng("salt_pepper_amount_range", [0.001, 0.05])
        lq_tensor = apply_salt_pepper(lq_tensor, random.uniform(lo, hi))

    if _p("vhs_prob") > 0 and random.random() < _p("vhs_prob"):
        lo, hi = _rng("vhs_strength_range", [0.1, 0.5])
        lq_tensor = apply_vhs(lq_tensor, random.uniform(lo, hi))

    if _p("aliasing_prob") > 0 and random.random() < _p("aliasing_prob"):
        lo, hi = _rng("aliasing_scale_range", [0.5, 0.85])
        lq_tensor = apply_aliasing(lq_tensor, random.uniform(lo, hi))

    if _p("interlace_weave_prob") > 0 and random.random() < _p("interlace_weave_prob"):
        lo, hi = _rng("interlace_weave_strength_range", [0.5, 1.0])
        lq_tensor = apply_interlace_weave(lq_tensor, random.uniform(lo, hi))

    if _p("interlace_flicker_prob") > 0 and random.random() < _p("interlace_flicker_prob"):
        lo, hi = _rng("interlace_flicker_strength_range", [0.1, 0.4])
        lq_tensor = apply_interlace_flicker(lq_tensor, random.uniform(lo, hi))

    if _p("interlace_blend_prob") > 0 and random.random() < _p("interlace_blend_prob"):
        lo, hi = _rng("interlace_blend_strength_range", [0.3, 1.0])
        lq_tensor = apply_interlace_blend(lq_tensor, random.uniform(lo, hi))

    if _p("film_grain_prob") > 0 and random.random() < _p("film_grain_prob"):
        lo, hi = _rng("film_grain_strength_range", [0.03, 0.12])
        gs_lo, gs_hi = _rng("film_grain_size_range", [1, 2])
        lq_tensor = apply_film_grain(lq_tensor, random.uniform(lo, hi),
                                     random.randint(int(gs_lo), max(int(gs_lo), int(gs_hi))))

    if _p("oversharp_prob") > 0 and random.random() < _p("oversharp_prob"):
        lo, hi = _rng("oversharp_strength_range", [0.5, 2.0])
        lq_tensor = apply_oversharpening(lq_tensor, random.uniform(lo, hi))

    if _p("scanlines_prob") > 0 and random.random() < _p("scanlines_prob"):
        sp_lo, sp_hi = _rng("scanlines_spacing_range", [2, 4])
        st_lo, st_hi = _rng("scanlines_strength_range", [0.2, 0.5])
        lq_tensor = apply_scanlines(lq_tensor,
                                    random.randint(int(sp_lo), max(int(sp_lo), int(sp_hi))),
                                    random.uniform(st_lo, st_hi))

    return lq_tensor
'''

NEOSR_HOOK_MARKER = "# === USR_STUDIO_CUSTOM_HOOK ==="

NEOSR_HOOK_CODE = '''
        # === USR_STUDIO_CUSTOM_HOOK ===
        try:
            from data._usr_studio_custom_degradations import custom_degrade
            _custom_opt = dict(self.opt) if hasattr(self, "opt") else {}
            try:
                import json as _j, os as _o
                _here = _o.path.dirname(_o.path.dirname(_o.path.abspath(__file__)))
                _sidecar = _o.path.join(_here, "_usr_studio_custom_deg.json")
                if _o.path.exists(_sidecar):
                    with open(_sidecar, "r", encoding="utf-8") as _f:
                        _custom_opt.update(_j.load(_f))
            except Exception:
                pass
            self.lq = custom_degrade(self.lq, _custom_opt)
        except Exception as _e:
            pass
        # === END USR_STUDIO_CUSTOM_HOOK ===
'''

_ALL_CUSTOM_KEYS = [
    # Custom 1
    "posterize_prob", "posterize_bits_range",
    "banding_prob", "banding_levels_range",
    "chroma_prob",
    "ca_prob", "ca_shift_range",
    "halation_prob", "halation_strength_range",
    "salt_pepper_prob", "salt_pepper_amount_range",
    "vhs_prob", "vhs_strength_range",
    # Custom 2
    "aliasing_prob", "aliasing_scale_range",
    "interlace_weave_prob", "interlace_weave_strength_range",
    "interlace_flicker_prob", "interlace_flicker_strength_range",
    "interlace_blend_prob", "interlace_blend_strength_range",
    "film_grain_prob", "film_grain_strength_range", "film_grain_size_range",
    "oversharp_prob", "oversharp_strength_range",
    "scanlines_prob", "scanlines_strength_range", "scanlines_spacing_range",
]


def install_patches(engine_dir: str, has_posterize: bool, has_banding: bool,
                    has_chroma: bool = False, has_ca: bool = False,
                    has_halation: bool = False, has_salt_pepper: bool = False,
                    has_vhs: bool = False, has_aliasing: bool = False,
                    has_interlace: bool = False, has_film_grain: bool = False,
                    has_oversharp: bool = False, has_scanlines: bool = False) -> bool:
    """
    Install the custom degradation patches into the engine's data/ directory.

    Returns True if patches were installed (or already up-to-date).
    """
    has_any = any([has_posterize, has_banding, has_chroma, has_ca,
                   has_halation, has_salt_pepper, has_vhs, has_aliasing,
                   has_interlace, has_film_grain, has_oversharp, has_scanlines])
    if not has_any:
        return uninstall_patches(engine_dir)

    if not os.path.isdir(engine_dir):
        return False

    data_dir = os.path.join(engine_dir, "data")
    if not os.path.isdir(data_dir):
        return False

    # 1. Write the patch module
    patch_path = os.path.join(data_dir, PATCH_FILENAME)
    try:
        with open(patch_path, "w", encoding="utf-8") as f:
            f.write(PATCH_CODE)
    except Exception as e:
        print(f"[Custom Deg] Erreur ecriture patch: {e}")
        return False

    # 2. Hook into the OTF dataset feed_data method
    otf_file = None
    for candidate in ["otf_dataset.py", "realesrgan_dataset.py", "otf.py"]:
        p = os.path.join(data_dir, candidate)
        if os.path.exists(p):
            otf_file = p
            break

    if not otf_file:
        print("[Custom Deg] Fichier OTF dataset non trouve, patch limite a copie")
        return True

    try:
        with open(otf_file, "r", encoding="utf-8") as f:
            src = f.read()

        if NEOSR_HOOK_MARKER in src:
            return True  # Already patched

        # Backup once
        backup = otf_file + ".usr_studio_backup"
        if not os.path.exists(backup):
            shutil.copy2(otf_file, backup)

        # Inject hook at end of feed_data method
        lines = src.split("\n")
        out_lines = []
        in_feed = False
        feed_indent = 0
        injected = False
        for i, line in enumerate(lines):
            out_lines.append(line)
            stripped = line.lstrip()
            if stripped.startswith("def feed_data") and not injected:
                in_feed = True
                feed_indent = len(line) - len(stripped)
                continue
            if in_feed and not injected:
                if i + 1 < len(lines):
                    next_line = lines[i + 1]
                    next_stripped = next_line.lstrip()
                    next_indent = len(next_line) - len(next_stripped)
                    is_end = (next_stripped.startswith("def ") and next_indent <= feed_indent) or \
                             (next_stripped == "" and i + 2 < len(lines) and
                              lines[i + 2].lstrip().startswith("def ") and
                              len(lines[i + 2]) - len(lines[i + 2].lstrip()) <= feed_indent)
                    if is_end and stripped:
                        hook_indented = "\n".join(
                            (" " * (feed_indent + 4) + l if l.strip() else l)
                            for l in NEOSR_HOOK_CODE.strip().split("\n")
                        )
                        out_lines.append(hook_indented)
                        injected = True
                        in_feed = False

        if not injected:
            print("[Custom Deg] Injection inline echouee, hook non installe")
            return True

        with open(otf_file, "w", encoding="utf-8") as f:
            f.write("\n".join(out_lines))

        print(f"[Custom Deg] Patches installes dans {os.path.basename(otf_file)}")
        return True
    except Exception as e:
        print(f"[Custom Deg] Erreur patch OTF: {e}")
        return False


def uninstall_patches(engine_dir: str) -> bool:
    """Restore the original OTF dataset file from backup."""
    if not os.path.isdir(engine_dir):
        return True
    data_dir = os.path.join(engine_dir, "data")
    if not os.path.isdir(data_dir):
        return True

    for candidate in ["otf_dataset.py", "realesrgan_dataset.py", "otf.py"]:
        p = os.path.join(data_dir, candidate)
        backup = p + ".usr_studio_backup"
        if os.path.exists(backup):
            try:
                shutil.copy2(backup, p)
            except Exception:
                pass

    patch_path = os.path.join(data_dir, PATCH_FILENAME)
    if os.path.exists(patch_path):
        try:
            os.remove(patch_path)
        except Exception:
            pass

    return True
